### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mp4096** [mp4096/indentex#17]
Most of the people I know use Windows for writing LaTeX. So it is imperative indentex has first-class Windows (7+) support.

Blocking issues:

- [x] Use [`termcolor`](https://crates.io/crates/termcolor) instead of [`ansi_term`](https://crates.io/crates/ansi_term) -- resolved (by removing colours altogether) in #20 
- [x] Compiling with MSVC so that indentex can be packed to a Windows installer together with C++ redistributable -- resolved in #26 
- [x] Create a Windows installer, probably using Wix. -- done by @syxolk in #28 
- [x] Do some AppVeyor Config-Fu to auto-deploy on tagged releases

**Comment by syxolk** [comment]
> Compiling with MSVC so that indentex can be packed to a Windows installer together with C++ redistributable

I've just found a configuration that works:
1. Install the [Build Tools für Visual Studio 2017](https://www.visualstudio.com/de/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15)
2. Install [rustup](https://www.rust-lang.org/en-US/install.html)
3. Use the stable-x86_64-pc-windows-msvc toolchain

**Comment by mp4096** [comment]
Great!

**Comment by syxolk** [comment]
> ... together with C++ redistributable

One can also use the linker flags `/MT` or `/MTd` to statically link the standard libraries. At least for an older project of mine the C++ Redistributable was no longer needed. However, I don't know how to do this in rust.

**Comment by mp4096** [comment]
This would be _so awesome_ if it works: https://github.com/rust-lang/libc/issues/290

**Comment by mp4096** [comment]
Ok, we'll probably need to bump Rust version to 1.14 in order to support static linking of CRT.

See [release notes for 1.14](https://blog.rust-lang.org/2016/12/22/Rust-1.14.html)

**Comment by mp4096** [comment]
I hope this will work for Win 7. MS CRT is [relatively new](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/)

**Comment by syxolk** [comment]
Stuff regarding the Wix installer:
- Icons for the installer and the executable
- Banner image for the installer
- Install directory (`Program files` or `AppData`)
- Add to `PATH` (user or system environment variables)
- How to update the version in the `wxs` file
- How to generate RTF from LICENSE.md (`pandoc -f markdown -t rtf LICENSE.md -s -o LICENSE.rtf`)

**Comment by mp4096** [comment]
> Banner image for the installer

[A blue to black gradient with a bold-italic caption](http://anyedit.sourceforge.net/Screenshotnsis.gif)


>Install directory (`Program files` or `AppData`)

`AppData` only, no option for system-wide installs.


> Add to `PATH` (user or system environment variables)

Yep.


> How to update the version in the `wxs` file
> How to generate RTF from LICENSE.md (`pandoc -f markdown -t rtf LICENSE.md -s -o LICENSE.rtf`)

I think the best way is to write a release script which does all this stuff automatically.

**Comment by syxolk** [comment]
https://github.com/syxolk/indentex/tree/wix-packaging

- [x] Install to `%LOCALAPPDATA%`
- [x] No UAC
- [x] Add install path to user's `%PATH%`

**Comment by mp4096** [comment]
Great!

Erm, how are we supposed to generate a GUID (`ProductUpgradeCode`)? Just take a random number and pray it's not already used?..

**Comment by syxolk** [comment]
I don't know about the component's GUID but the `UpgradeCode` must be unique.

http://wixtoolset.org/documentation/manual/v3/howtos/general/generate_guids.html

**Comment by mp4096** [comment]
Ok, I see. Thanks!

We still have to find out how to link CRT statically. I'll make a separate issue for it.

**Comment by mp4096** [comment]
After studying [RFC 1721](https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md), I think that static linking can be enforced by passing a `target-feature=+crt-static` flag to `rustc`.

Hence, we need to call `cargo` like this:

```
RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-pc-windows-msvc
```

**Comment by mp4096** [comment]
:roll_eyes: 

[`error: failed to run rustc to learn about target-specific information
`](https://ci.appveyor.com/project/mp4096/indentex/build/job/b8bh01vblo89d305)

**Comment by mp4096** [comment]
Continued in #31
